import { existsSync, readFileSync, writeFileSync } from 'fs'
import { resolve } from 'path'

function toKebabCase(name) {
  return name
    .replace(/^Cp/, 'cp-')
    .replace(/([a-z0-9])([A-Z])/g, '$1-$2')
    .toLowerCase()
}

function getComponentNames(componentsRoot) {
  const componentsIndexPath = resolve(componentsRoot, 'index.ts')
  const indexContent = readFileSync(componentsIndexPath, 'utf8')
  const exportModules = [...indexContent.matchAll(/export\s+\*\s+from\s+['"]\.\/([^'"]+)['"]/g)].map((match) => match[1])

  const names = new Set()
  for (const moduleName of exportModules) {
    const moduleEntryPath = resolve(componentsRoot, moduleName, 'index.ts')
    if (!existsSync(moduleEntryPath)) continue

    const moduleContent = readFileSync(moduleEntryPath, 'utf8')
    const componentMatches = [...moduleContent.matchAll(/export\s+const\s+(Cp[A-Za-z0-9]+)\s*=\s*withInstall/g)]
    for (const match of componentMatches) {
      names.add(match[1])
    }
  }

  return [...names].sort((a, b) => a.localeCompare(b))
}

function generateGlobalTypes(packageName, componentNames) {
  const lines = componentNames.map((name) => `    ${name}: typeof import('${packageName}')['${name}']`)
  return `/* eslint-disable */
// Auto-generated by scripts/generate-meta.mjs. Do not edit.
declare module 'vue' {
  export interface GlobalComponents {
${lines.join('\n')}
  }
}

export {}
`
}

function generateWebTypes(packageName, packageVersion, componentNames) {
  const tags = componentNames.map((name) => ({
    name: toKebabCase(name),
    source: {
      module: packageName,
      symbol: name
    }
  }))

  return {
    $schema: 'https://raw.githubusercontent.com/JetBrains/web-types/master/schema/web-types.json',
    name: packageName,
    version: packageVersion,
    framework: 'vue',
    'js-types-syntax': 'typescript',
    contributions: {
      html: {
        tags
      }
    }
  }
}

function main() {
  const packageRoot = resolve(import.meta.dirname, '..')
  const componentsRoot = resolve(packageRoot, '../components')
  const packageJsonPath = resolve(packageRoot, 'package.json')
  const packageJson = JSON.parse(readFileSync(packageJsonPath, 'utf8'))

  const componentNames = getComponentNames(componentsRoot)
  if (componentNames.length === 0) {
    throw new Error('No installable components found in packages/components.')
  }

  const globalTypesPath = resolve(packageRoot, 'global.d.ts')
  const webTypesPath = resolve(packageRoot, 'web-types.json')

  writeFileSync(globalTypesPath, generateGlobalTypes(packageJson.name, componentNames), 'utf8')
  writeFileSync(webTypesPath, `${JSON.stringify(generateWebTypes(packageJson.name, packageJson.version, componentNames), null, 2)}\n`, 'utf8')

  console.log(`[meta] Generated ${componentNames.length} components into global.d.ts and web-types.json`)
}

main()
